name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: cfn-lint
      uses: docker://scottbrenner/cfn-lint-action:latest
      with:
        args: **/*.yaml